# Generated by Django 2.2.16 on 2023-03-09 20:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230309_2321'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='Вы не можете подписаться на себя'),
        ),
    ]
